### ISSUE TITLE
IRC channel topic

### ISSUE THREAD

**Issue by dotlambda** [simplebot-org/simplebot_plugins#17]
When sending a message to a bridged group, the IRC bot should use the IRC channel's topic as its signature.

**Comment by adbenitez** [comment]
hi, there is a command to see channel topic, you just have to send that in the channel you want to see the topic

**Comment by adbenitez** [comment]
the IRC plugin is quite alpha, but I don't think I will set topic in the bot status because that will override the bot status shown in profile, also changing the status is a global setting, right after you change it another thread could change it and you send a different signature, that would need per message signatures

**Comment by dotlambda** [comment]
> that will override the bot status shown in profile

True, that's problematic.



> changing the status is a global setting, right after you change it another thread could change it and you send a different signature, that would need per message signatures

yes that would have to be changed in core
